FROM python:3.11-slim

WORKDIR /app

COPY recommendation_requirements.txt ./
RUN pip install --no-cache-dir -r recommendation_requirements.txt

COPY recommendation ./recommendation
COPY recommendation_app.py ./

EXPOSE 8002

CMD ["python", "-m", "uvicorn", "recommendation_app:app", "--host", "0.0.0.0", "--port", "8002", "--workers", "1"]
